### ISSUE TITLE
你好 作者 有问题咨询下

### ISSUE THREAD

**Issue by Marin9527** [panlongpl/movieRcommend#3]

**Comment by Marin9527** [comment]
页面海报显示不了 我去数据库复制图片链接在网页加载一张 再刷新页面 就显示他那一张了是什么问题

**Comment by panlongpl** [comment]
我数据库存的是图片的网页的地址，程序里用的也是网页地址，你自己复制url在浏览器上打开，本地就会有图片的缓存资源。至于如何解决这个问题，你可以把这些图片下载到本地，然后图片用本地路径。如果希望用图片的url去显示图片，这个我也不太懂。

**Comment by Marin9527** [comment]
> 我数据库存的是图片的网页的地址，程序里用的也是网页地址，你自己复制网址在浏览器上打开，本地就会有图片的缓存资源。至于如何解决这个问题，你可以把这些图片下载到本地，然后图片用本地路径。如果希望用图片的url去显示图片，这个我也不太懂。

就是我要一张一张复制网址在浏览器上打开吗 - -哦 你的意思是你没下载图片 懂了

**Comment by panlongpl** [comment]
嗯，当时我只是想展示一下效果，所以懒得下载图片，views中有一段注释掉的代码可以根据url在浏览器中加载图片。

**Comment by Marin9527** [comment]
> 嗯，当时我只是想展示一下效果，所以懒得下载图片，views中有一段注释掉的代码可以根据网址在浏览器中加载图片。

明白 十分感谢

**Comment by 906571331** [comment]
作者您好，在声明使用到了您的源代码后，可以在其他程序中使用您的源代码吗？
